config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "shopify_auth#login"
  root "products#index"
  post "products/import_json", to: "products#import_json", as: :import_products_from_json
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/product.rb
class Product
  # get products from shopify
  def get_products
    RestClient.get(
      "https://latori-teststore.myshopify.com/admin/api/2023-01/products.json",
      {
        'X-Shopify-Access-Token'=> ENV['ACCESS_TOKEN']
      }
    )
  end

  def update_product?(product_id, product)
    resp = RestClient.put(
      "https://latori-teststore.myshopify.com/admin/api/2023-01/products/#{product_id}.json",
      {
        product: {
          title:      product['data']['resource']['title'],
          body_html:  product['data']['resource']['description'],
          images:     product['data']['resource']['images'],
          status:     product['data']['resource']['status'] == 'inactive' ? 'draft' : product['data']['resource']['status'],
          tags:       product['data']['resource']['tags'].split(',')
        }
      },
      {
        'X-Shopify-Access-Token'=> ENV['ACCESS_TOKEN']
      }
    )
    resp.code == 200
  end

  # add a product on shopify
  def add_product?(product)
    resp = RestClient.post(
      "https://latori-teststore.myshopify.com/admin/api/2023-01/products.json",
      {
        product: {
          title:      product['data']['resource']['title'],
          body_html:  product['data']['resource']['description'],
          images:     product['data']['resource']['images'],
          status:     product['data']['resource']['status'] == 'inactive' ? 'draft' : product['data']['resource']['status'],
          tags:       product['data']['resource']['tags'].split(',')
        }
      },
      {
        'X-Shopify-Access-Token'=> ENV['ACCESS_TOKEN']
      }
    )
    resp.code == 201
  end

  # delete a product from shopify
  def delete_product?(product_id)
    resp = RestClient.delete(
      "https://latori-teststore.myshopify.com/admin/api/2023-01/products/#{product_id}.json",
      {
        'X-Shopify-Access-Token'=> ENV['ACCESS_TOKEN']
      }
    )

    resp.code == 200
  end

  # check if the product from json file exists on shipify
  def exist_product?(product)
    product_id = nil

    resp = RestClient.get(
      "https://latori-teststore.myshopify.com/admin/api/2023-01/products.json",
      {
        'X-Shopify-Access-Token'=> ENV['ACCESS_TOKEN']
      }
    )

    exist_products = JSON.parse(resp)['products']

    if exist_products.present?
      exist_products.each do |exist_product|
        if exist_product['title'] == product['data']['resource']['title']
          product_id = exist_product['id']
          break
        end
      end
    end

    product_id
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  require 'securerandom'

  def index
    response = Product.new.get_products
    @products = JSON.parse(response)['products']
  end

  def import_json
    json_file = product_params[:json_file]

    # store uploaded json data into redis with uuid
    uuid = SecureRandom.uuid
    cached_json_list = Rails.cache.redis.get("json_data_list")

    if cached_json_list.present?
      Rails.cache.redis.set("json_data_list", "#{cached_json_list},#{uuid}")
    else
      Rails.cache.redis.set("json_data_list", uuid)
    end

    Rails.cache.redis.set("json_data_#{uuid}", json_file.read)

    redirect_to root_path
  end

  private
  def product_params
    params.require(:product).permit(:json_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SynchronizeShopifyProducts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<div class="container-xl">
  <h1>Products</h1>

  <%= form_for(:product, url: import_products_from_json_path, method: :post, data: {remote: true}, id: "csv-form") do |f| %>
    <div class="custom-file mb-3 mt-3">
<!--      <input type="file" class="custom-file-input" id="customFile">-->
      <%= f.file_field :json_file, multiple: false, required: true, accept: 'application/json', class: 'custom-file-input' %>
      <label class="custom-file-label" for="customFile">Choose JSON file</label>
    </div>
    <%= f.submit "Import", class: 'btn btn-primary flex-fill ml-1'%>
  <% end %>

  <table class="table">
    <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Title</th>
      <th scope="col">Created time</th>
      <th scope="col">Updated time</th>
    </tr>
    </thead>

    <% @products.each do |product| %>
      <tr>
        <td><%= product['id'] %></td>
        <td><%= product['title'] %></td>
        <td><%= product['created_at'] %></td>
        <td><%= product['updated_at'] %></td>
      </tr>
    <% end %>
  </table>
</div>